version: '3.1'
services:
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
    db:
        image: 'postgres:9.6-alpine'
        container_name: voceazul-postgres
        working_dir: /application
        environment:
            - POSTGRES_USER=homestead
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=homestead
        volumes:
            - '.:/application'
        
        ports:
            - '5432:5432'
    memcached:
        image: 'memcached:alpine'
        container_name: voceazul-memcached
    redis:
        image: 'redis:alpine'
        container_name: voceazul-redis
    elastic:
        image: elasticsearch
        container_name: voceazul-elastic
        ports:
            - '9201:9200'
    mariadb:
        image: 'mariadb:10.1'
        container_name: voceazul-mariadb
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/data/database:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
        ports:
            - '3337:3306'
    webserver:
        image: 'nginx:alpine'
        container_name: voceazul-webserver
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
    php-fpm:
        build: docker/php-fpm
        container_name: voceazul-php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini'
